### ISSUE TITLE
Namespaced page blocks localization

### ISSUE THREAD

**Issue by hazg** [comfy/comfortable-mexican-sofa#679]
How to localize namespaced page blocks?

For ex. to localize {{ cms:page:some_label:rich_text }}
just add to yml:

``` yaml
  activerecord:
    attributes:
      comfy/cms/page:
        "some_label": "Some label"
```

but if i try to
{{ cms:page:some_namespace.some_label:rich_text }}
with 

``` yaml
  activerecord:
    attributes:
      comfy/cms/page:
        "some_namespace.some_label": 'Some namespaced label"
```

nothing happend.

Also, i can't translate tabs names.
